import logo from './logo.svg';
import './App.css';
import React from 'react';
import InputSlider from './components/Slider';

function App() {
  const value=26;
  const value1=23;
  const value2=24;
  const value3=25;
  const [selected, setSelected] = React.useState(0);


  const updateDistance = (event) => {

    if(selected == 1){ // kg
      value1  = value//: calc(value) calculos para peso
    } else if(selected == 2){ // °C
      value2  = value//: calc(value) calculos para temperatura
    } else if(selected == 3){ // l
      value3  = value//: calc(value) calculos para volumen
    }


    // remove the last 2 characters and the first 1 character, the characters are generated by the server.
    let parsed_string = event.data.slice(1, -3);
    console.log("event data:" + parsed_string);

    
    const invert_bits = false;
    if (parsed_string != "00000000" && parsed_string != "11111111") {
      if (invert_bits) {
        parsed_string = parsed_string.split('').map((c) => {
          return c === '1' ? '0' : '1'; // XOR
        }).join('');
        console.log("bits invertidos: " + parsed_string); 
      }
      console.log("actualizando valores de detalles");
      // setValue(value);
    }


  }

  //handleSelect
  const handleSelect = (event) => {
    console.log("handleSelect");
    console.log(event.target.value);
    let toSend = 0;
    
    setSelected(event.target.value);
    if (selected) {
      toSend = selected -1;
    } 

    fetch('http://localhost:5000/selected', {
      method: 'POST',
      body: JSON.stringify({
        selected: toSend
      })
    })
  }


  // create a react effect to subscribe to the server-sent events
  React.useEffect(() => {
    const sse = new EventSource("http://localhost:5000/stream");
    sse.onmessage = updateDistance;
  }, []);


  return (
    <div className="App">
      <header className="App-header">
        <div class="container text-center">
          <div class="row">
            <div class="col">
              <InputSlider value={value1} unit={'kg'} visible />
              <button value={1} onClick={handleSelect} class="btn btn-dark"> Seleccionar</button>
            </div>
            <div class="col">
              <InputSlider value={value2} unit={'°C'} visible />
              <button value={2} onClick={handleSelect} class="btn btn-dark"> Seleccionar</button>
            </div>
            <div class="col">
              <InputSlider value={value3} unit={'l'} visible />
              <button value={3} onClick={handleSelect} class="btn btn-dark"> Seleccionar</button>
            </div>
          </div>
        </div>
      </header>
    </div>
  );
}

export default App;
